-- homs_ledger_schema.sql
-- D1 database: homs-ledger
--
-- One row per money movement generated by a settled booking. Materialized
-- at settlement time (see src/ledger.js, called from payment.js's settle())
-- rather than computed on read, so a statement is a plain GROUP BY over
-- facts already written -- not a recomputation of booking-composer's split
-- logic a second time in SQL.
--
-- category classifies what counts as real income vs money just passing
-- through this ledger:
--   income        -- owner/manager's actual earnings (rent split, cleaning)
--   liability     -- guest's deposit, held not earned (excluded from income)
--   pass_through  -- processing fee, retained by whoever received the funds,
--                    never split (excluded from income)
--   shadow        -- informational only, no real money moved (the
--                    "what an OTA would have charged" comparison)
--
-- amount_minor is an INTEGER in minor currency units (cents) -- D1/SQLite
-- has no fixed-point decimal type, and floats would drift under repeated
-- aggregation across a statement period.

CREATE TABLE IF NOT EXISTS ledger_entries (
  id            INTEGER PRIMARY KEY AUTOINCREMENT,
  location_id   TEXT NOT NULL,
  booking_id    TEXT NOT NULL,
  invoice_number TEXT,
  invoice_id    TEXT,
  recipient     TEXT NOT NULL CHECK (recipient IN ('owner','manager','guest','platform')),
  recipient_name TEXT,
  category      TEXT NOT NULL CHECK (category IN ('income','liability','pass_through','shadow')),
  entry_type    TEXT NOT NULL,
  amount_minor  INTEGER NOT NULL,
  currency      TEXT NOT NULL DEFAULT 'USD',
  description   TEXT,
  source        TEXT NOT NULL DEFAULT 'payment_confirmed',
  reconciled    INTEGER NOT NULL DEFAULT 0,
  created_at    TEXT NOT NULL DEFAULT (datetime('now'))
);

-- One row per (booking, entry_type) for the initial settlement pass -- this
-- is what makes writeLedgerEntries() safe to call more than once for the
-- same booking without double-counting. Doesn't yet cover reschedule/
-- cancellation-driven entries on the SAME booking (those need a broader key
-- including a capture/refund reference) -- deliberately out of scope for
-- this pass; today's ledger only writes from payment.js's settle().
CREATE UNIQUE INDEX IF NOT EXISTS idx_ledger_booking_entry_type
  ON ledger_entries(booking_id, entry_type);

CREATE INDEX IF NOT EXISTS idx_ledger_location ON ledger_entries(location_id);
CREATE INDEX IF NOT EXISTS idx_ledger_location_recipient_category
  ON ledger_entries(location_id, recipient, category);
CREATE INDEX IF NOT EXISTS idx_ledger_created_at ON ledger_entries(created_at);

-- ---------------------------------------------------------------------------
-- Reference queries -- what src/reports.js actually runs. Not migrations.
-- ---------------------------------------------------------------------------

-- Owner statement: income earned + shadow OTA comparison, one location.
-- SELECT
--   entry_type, currency,
--   SUM(amount_minor) AS total_minor,
--   COUNT(*) AS entry_count
-- FROM ledger_entries
-- WHERE location_id = ?1 AND recipient = 'owner'
--   AND created_at >= ?2 AND created_at < ?3
-- GROUP BY entry_type, currency;

-- Manager statement: same shape, recipient = 'manager'.

-- Reconciliation: bookings this ledger has an income row for for the period.
-- SELECT DISTINCT booking_id, invoice_number
-- FROM ledger_entries
-- WHERE location_id = ?1 AND category = 'income'
--   AND created_at >= ?2 AND created_at < ?3;
-- (diffed in JS against a GHL list-transactions pull for the same window --
-- see src/reports.js's handleReconcile)
